### ISSUE TITLE
Loss of data

### ISSUE THREAD

**Issue by lmm2000** [dianixn/Signal_detection_OFDMPowerofDNN#1]
Hi, it's really great work that inspires me a lot. But when conducting the procedure, there'll always be some problems.
For example, when conducting Demonstration_of_papers_DNN_classification.m, the error will be loss of 'DNN_Classification_Trained.mat'; so I turn to DNN_Classification_Trained.m, then the whole procedure will **stop at a function** that is built in matlab.
BTW, I have also tried other functions and the same result will occur.
If possible, can you please help me with this? Like upgrading your .mat files?

**Comment by dianixn** [comment]
Hi, yes, it does not work in that way. You need to run DNN_Regression_Image_SER_Test.m to ontain an DNN_trained which is a trained NN, and save that as DNN_Classification_Trained.mat with commend save('DNN_Classification_Trained.mat', 'DNN_trained'). It allows you to make changes to training options so you can try some changes in changes to see if you can improve the performance.

The file is larger that the limitation for uploading but you can run it by yourself to have a DNN of yours!

**Comment by dianixn** [comment]
Is that solved?

**Comment by lmm2000** [comment]
> 
> 
> Is that solved?

thanks for your help, and I've tried running **DNN_Classification_SER_Test.m** but there is still another mistake in trainNetwork(): 
<img width="620" alt="ERROR" src="https://user-images.githubusercontent.com/35120823/114796814-69da5800-9dc4-11eb-887e-12a5ebfaff9e.PNG">

but DNN_Regression_Image_SER_Test.m runs fine. So is the difference determined by the network structure? I think I will try changing the original structure later.

**Comment by dianixn** [comment]
我说错了，是运行DNN_Regression_Image_SER_Test.m，没有DNN_Classification_SER_Test.m那个文件，你也可以和作者的代码对比一下，用的python
I was wrong, it's DNN_Regression_Image_SER_Test.m, not DNN_Classification_SER_Test.m and there is no DNN_Classification_SER_Test.m. You also can compare the layers with original, I think I was using the same layers and size as original paper.

**Comment by dianixn** [comment]
诶，我没说错，我说的是You need to run DNN_Regression_Image_SER_Test.m to ontain an DNN_trained，没有DNN_Classification_SER_Test.m这个文件，save('DNN_Classification_Trained.mat', 'DNN_trained')然后有一个DNN_Classification_Trained.mat，不要改成.m因为还要load回去

**Comment by dianixn** [comment]
1. Run DNN_Regression_Image_SER_Test.m
2. Type in save('DNN_Trained','DNN_Trained')
3. Open Demonstration_of_papers_DNN.m
4. There's a load commend of load('DNN_Trained.mat'); You did generate a DNN_Trained.mat from step2, **do not change it to .m or others**.
5. Run Demonstration_of_papers_DNN.m

I hope it is clear and when you play with the rest, remember to generate the corresponding DAG network as the steps mentioned.

**Comment by dianixn** [comment]
哦我知道为什么了，你在运行DNN_Classification_Trained.m的时候要把path换到那个文件夹里，因为虽然都叫Data_generation.m但是里面不太一样，我感觉太麻烦了都放在the rest一起了。要不你给我个邮箱我直接发你一个训练好的，github有上传大小限制，这换来换去的好心累。

**Comment by lmm2000** [comment]
> 
> 
> 哦我知道为什么了，你在运行DNN_Classification_Trained.m的时候要把path换到那个文件夹里，因为虽然都叫Data_generation.m但是里面不太一样，我感觉太麻烦了都放在the rest一起了。要不你给我个邮箱我直接发你一个训练好的，github有上传大小限制，这换来换去的好心累。
啊这！我直呼好兄弟 哇太谢谢了 我这几天有点忙 就没及时看消息 
我的邮箱是1055429603@qq.com 谢谢~
